language: node_js
services:
  - docker
sudo: false
node_js:
  - 'lts/carbon'
  - 'lts/*'
script:
  - yarn install
  - commitlint-travis
  - yarn license
  - yarn lint
  - yarn code:build
  - yarn test:all
  - yarn build:docker
